# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'VPNFaster' do
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'BlocksKit'
  pod 'SDWebImage'
  pod 'libPhoneNumber-iOS'
  pod 'MJRefresh'
  pod 'SWTableViewCell'
  pod 'DACircularProgress'
  
  pod 'AFNetworking'
  #pod 'SSZipArchive'
  
  pod 'SAMKeychain'
  
  pod 'YYModel'
  pod 'Reachability'

  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCAnalytics'
  pod 'UMCErrorCatch'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
end
