#use_frameworks!

target 'rrmapanalyzer' do
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'BlocksKit'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'SWTableViewCell'
  pod 'DACircularProgress'

  pod 'AFNetworking'
  pod 'SSZipArchive'

  pod 'YYModel'
  pod 'Reachability'
  pod 'Masonry'

end
